#pragma once
#include <dirent.h>
#include <pthread.h>
#include <unistd.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include "kmstructs.h"
#include "general.h"
#include "pidtree.h"
#include "cbdefine.h"
#include "callbacks.h"
#include "managethread.h"
#include <sys/resource.h>
#include "pglobal.h"
#include "taskopt.h"
// 处理信号以及事件
// 参数1：当前pid
// 参数2：当前返回状态
// 参数3：函数返回值
void sigEvt(PidInfo *pinfo, TASKTYPE *type);
